# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: DockerHub

  - name: imageName
    value: 'headless-k-worker'
  - name: taggedImage
    value: '$(imageName):$(build.buildId)'
  - name: taggedImageLatest
    value: '$(imageName):latest'
  - name: BUILD_ID
    value: '$(build.buildId)'
  - name: DOCKER_CLI_EXPERIMENTAL
    value: enabled
  - name: buildPlatforms
    value: linux/amd64,linux/arm/v7

steps:
  - script: |
      export DOCKER_CLI_EXPERIMENTAL=enabled

      docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
      docker login -u $(DOCKER_LOGIN) -p $(DOCKER_PASSWORD)
      docker buildx version
      docker buildx create --use --name my-builder
      docker buildx build \
        -t $(DOCKER_LOGIN)/$(taggedImage) \
        -t $(DOCKER_LOGIN)/$(taggedImageLatest) \
        --platform $(buildPlatforms) \
        --build-arg BUILD_ID=$(BUILD_ID) \
        . --push
    displayName: 'docker build'

