apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  # how many empty replicasets should last
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: worker
  replicas: 1
  template:
    metadata:
      labels:
        run: worker
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: $(Build.Definitionname):$(Build.BuildId)
          imagePullPolicy: Always
          env:
            - name: EMAIL
              value: $(EREP_EMAIL)
            - name: PASSWORD
              value: $(EREP_PASSWORD)
            - name: SERVER_URL
              value: 'https://$(SERVER_DOMAIN)'
            - name: SERVER_TOKEN
              value: $(WORKER_TOKEN)
            # This is so that k8s refetches latest image
            - name: RELEASE_ID
              value: '$(Release.DeploymentId)'
          volumeMounts:
            - mountPath: /usr/app/src/logs
              name: worker-logs
      volumes:
        - name: worker-logs
          persistentVolumeClaim:
            claimName: worker-volume-claim
