apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-volume
  namespace: headless-k
  labels:
    for_app: worker
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/app/src/logs"
