kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: worker-volume-claim
spec:
  selector:
    matchLabels:
      for_app: worker
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
