apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  # how many empty replicasets should last
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      run: worker
  replicas: 1
  template:
    metadata:
      labels:
        run: worker
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker
          image: $(Build.Definitionname)
          imagePullPolicy: Always
          env:
            - name: ERPK_RM
              value: $(ERPK_RM)
            # This is so that k8s refetches latest image
            - name: RELEASE_ID
              value: '$(Release.DeploymentId)'
